//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nhif.bg/xsd/hosp/cp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://nhif.bg/xsd/hosp/cp", IsNullable=false)]
public partial class Protocol_DrugTherapy {
    
    private Protocol_DrugTherapyPart_Chemotherapy part_ChemotherapyField;
    
    /// <remarks/>
    public Protocol_DrugTherapyPart_Chemotherapy Part_Chemotherapy {
        get {
            return this.part_ChemotherapyField;
        }
        set {
            this.part_ChemotherapyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nhif.bg/xsd/hosp/cp")]
public partial class Protocol_DrugTherapyPart_Chemotherapy {
    
    private Protocol_DrugTherapyPart_ChemotherapyGen_Markers gen_MarkersField;
    
    /// <remarks/>
    public Protocol_DrugTherapyPart_ChemotherapyGen_Markers Gen_Markers {
        get {
            return this.gen_MarkersField;
        }
        set {
            this.gen_MarkersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nhif.bg/xsd/hosp/cp")]
public partial class Protocol_DrugTherapyPart_ChemotherapyGen_Markers {
    
    private string[] nameField;
    
    private bool[] signField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name")]
    public string[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Sign")]
    public bool[] Sign {
        get {
            return this.signField;
        }
        set {
            this.signField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nhif.bg/xsd/hosp/cp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://nhif.bg/xsd/hosp/cp", IsNullable=false)]
public partial class cpFile {
    
    private Protocol_DrugTherapy[] protocol_DrugTherapyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Protocol_DrugTherapy")]
    public Protocol_DrugTherapy[] Protocol_DrugTherapy {
        get {
            return this.protocol_DrugTherapyField;
        }
        set {
            this.protocol_DrugTherapyField = value;
        }
    }
}
